# Generated by Django 5.2.5 on 2025-08-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_last_video_update_videosyncdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
