# Generated by Django 5.2.5 on 2025-08-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_participant_is_muted_participant_muted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='banned_words',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
