# Generated by Django 5.2.5 on 2025-08-31 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_room_banned_words'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='kicked_users',
            field=models.ManyToManyField(blank=True, related_name='kicked_from_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
