# Generated by Django 5.2.5 on 2025-08-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_room_kicked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='kicked_users',
        ),
    ]
